### ISSUE TITLE
metrics error

### ISSUE THREAD

**Issue by arunodhayan** [sharathadavanne/seld-dcase2020#3]
in the new updated metrics

Epoch 1/5
 - 25s - loss: 0.3051 - sed_out_loss: 0.0080 - doa_concat_loss: 2.9709e-04
Epoch 2/5
 - 25s - loss: 0.3038 - sed_out_loss: 0.0080 - doa_concat_loss: 2.9579e-04
Epoch 3/5
 - 25s - loss: 0.2957 - sed_out_loss: 0.0081 - doa_concat_loss: 2.8764e-04
Epoch 4/5
 - 25s - loss: 0.2985 - sed_out_loss: 0.0076 - doa_concat_loss: 2.9094e-04
Epoch 5/5
 - 25s - loss: 0.3383 - sed_out_loss: 0.0135 - doa_concat_loss: 3.2480e-04
/src/metrics/evaluation_metrics.py:531: RuntimeWarning: invalid value encountered in arccos
  dist = np.arccos(x1*x2 + y1*y2 + z1*z2) * 180 /np.pi

i get this error at my 85th epoch

**Comment by sharathadavanne** [comment]
Hi @arunodhayan this is happening because the value x1x2 + y1y2 + z1*z2 is goint beyond the range of [-1 1]. I have updated the code just now to handle this. If you dont want to pull the entire code, you can just edit the[ following changes in your version](https://github.com/sharathadavanne/seld-dcase2020/commit/ad63358e1e50e8ed8effab829fefbc9488b87a87).

**Comment by arunodhayan** [comment]
Thank you for the update
