### ISSUE TITLE
for the evaluation 

### ISSUE THREAD

**Issue by arunodhayan** [sharathadavanne/seld-dcase2020#5]
for the evaluation do we need to write a seperate script to evaluate the dataset

**Comment by sharathadavanne** [comment]
Yes, based on your evaluation setup you might have to write your own script. However, if you are using this baseline script, then after downloading the evaluation dataset, you can run the baseline code in evaluation mode by setting mode='eval'  in [parameter.py file here](https://github.com/sharathadavanne/seld-dcase2020/blob/94218c97e19fbe86e5056d1524a780479abace00/parameter.py#L24). This will use a different partition of the development set to select the best model, and use it on the evaluation set. It additionally dumps the results for each file in the evaluation set, which you can submit for the challenge.

**Comment by arunodhayan** [comment]
i had checked with your baseline script i tried to set the mode to eval and run python seld.py 'arg for eval' it is training again ? and dumpimg only 40 files to results directory??

**Comment by sharathadavanne** [comment]
Yes, it will start training again, because unlike in dev set where we keep some data as unseen, for eval set, we use all data from dev set for training, and then choose the best model to test on eval set.

Regarding the number of files,  there should be 200 files in total and not 40, this 200 is equal to the number of recordings in the eval set. There was a small change in the data_generator class specifically for a bug in eval set, that we updated recently.  You can [find here the changes.](https://github.com/sharathadavanne/seld-dcase2020/commit/74a0e1db61cee32c19ea9dde87ba1a5389eb9a85). Ideally, self._filenames_list should consist of all the 200 file names. See if this helps.

**Comment by JNaranjo-Alcazar** [comment]
Yes! 
I have faced the same issue and it has been solved by the changes mentioned.

Thanks for the issue I was starting to panic :)

**Comment by JNaranjo-Alcazar** [comment]
Hi again!

I have the 200 csv prepared for submission. I have checked in the website that it says 800 csvs. Is it strictly necessary to send the 800 csvs or is the 200 csv evaluation sufficient? In the case of the 800, how do I calculate the remaining 600 with the model already trained using the code of this repo?

Thanks in advance,

Javi

**Comment by polarch** [comment]
Hi, that number in the submission page of the website was wrong. It should be fixed now. The 200 CSV evaluation files are sufficient.
